use_frameworks!

target 'PinwheelSDK_Example' do
  pod 'PinwheelSDK', :path => '../'

  target 'PinwheelSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 5.0.1'
    pod 'Nimble', '~> 10.0.0'
  end
end
