use_frameworks!

target 'PinwheelSDK_Example' do
  pod 'PinwheelSDK', :path => '../'

  target 'PinwheelSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 9.0.1'
  end
end
