export API_SECRET=
export FL_AWS_DEVICE_FARM_NETWORK_PROFILE_ARN=
export FL_AWS_TEST_SPEC=
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_SESSION_TOKEN=
export AWS_PROFILE=
export MATCH_PASSWORD=
