default_platform(:ios)

platform :ios do

  desc "Release a new version with a patch bump_type"
  lane :patch do
    bump_and_release("patch") # we could use __method__.to_s instead of duplicating the name
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    bump_and_release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    bump_and_release("major")
  end

  desc "Release the current version"
  lane :release_current do
    podspec_name = "PinwheelSDK.podspec"
    pod_lib_lint
    version = version_get_podspec(path: podspec_name)
    release(version)
  end

  def bump_and_release(type)
    podspec_name = "PinwheelSDK.podspec"
    pod_lib_lint
    version = version_bump_podspec(path: podspec_name,
                                   bump_type: type)
    git_add(path: podspec_name)
    git_commit(path: [podspec_name],
              message: "#{version} release")
    release(version)
  end

  def release(version)
    add_git_tag(tag: "#{version}")
    push_to_git_remote
    pod_push
  end
end